### ISSUE TITLE
Everything worked except lsgkm when I was reproducing figure 2b? 

### ISSUE THREAD

**Issue by guthrey1** [kipoi/manuscript#7]
I added my figures and excel data: 
When I was running the predictions for lsgkm on the transcription factors it took days on each one so I manually stopped the job after 3 days. If this caused the data to be unreadable how can I mark the lsgkm predictions so that they will at least give some auprc data? 

[all_models.chr8.DNASE-peaks.pdf](https://github.com/kipoi/manuscript/files/3479187/all_models.chr8.DNASE-peaks.pdf)
[all_models.chr8.pdf](https://github.com/kipoi/manuscript/files/3479188/all_models.chr8.pdf)
[all_models.chr8 word.txt](https://github.com/kipoi/manuscript/files/3479190/all_models.chr8.word.txt)

**Comment by krrome** [comment]
Hi, Unfortunately lsgkm is very slow and also for us it took days to compute it. I am not sure what you mean by some auprc data - you could always restrict the prediction to a smaller genomic region by for example subsetting the input files. This will give you some result that shows that the code works, but won't reproduce the exact results in the manuscript. For that you would have to wait until lsgkm is finished or you could try to run the lsgkm predictions in parallel by splitting the input file and using e.g. gnu parallel (https://www.gnu.org/software/parallel/) on the kipoi predict command for lsgkm. In that case you would then have to merge the output files into one file again after execution...
I hope this helps,
Roman

**Comment by guthrey1** [comment]
I will attempt to rerun lsgkm in parallel for each transcription factor. But, the first time I was doing this I noticed that lsgkm froze at 2% after just 12 minutes and did not send further log information for days until I quit it. Is this normal? If not what could be the issue?
